# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'buy3.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QDialog
import sys

class Buy_Form(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(320, 248)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(51, 20, 96, 12))
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(21, 50, 151, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ButtonGetAdvantage = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ButtonGetAdvantage.setObjectName("ButtonGetAdvantage")
        self.verticalLayout.addWidget(self.ButtonGetAdvantage)
        self.ButtonCompare = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ButtonCompare.setObjectName("ButtonCompare")
        self.verticalLayout.addWidget(self.ButtonCompare)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(220, 170, 61, 61))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.ButtonGetAdvantage.clicked.connect(self.getAdvantagePage)
        self.ButtonCompare.clicked.connect(self.analysis)
        self.pushButton_3.clicked.connect(self.recommandpart)
        from PyQt5.QtGui import QIcon
        Dialog.setWindowIcon(QIcon("util/huohuo.png"))
        Dialog.setStyleSheet("background-color: #ffffff ;")

        image_path = f"util/AI.png"
        from PyQt5.QtGui import QPixmap
        # image_path = f"images/{selected_option.lower()}.jpg"  # 假设图片路径与选项名字相同
        pixmap = QPixmap(image_path)
        self.label_2.setPixmap(pixmap)
        self.label_2.setScaledContents(True)

    # def retranslateUi(self, Dialog):
    #     _translate = QtCore.QCoreApplication.translate
    #     Dialog.setWindowTitle(_translate("Dialog", "AI Choice"))
    #     # self.label_5.setText(_translate("Dialog", "功能描述："))
    #     self.label.setText(_translate("Dialog", "请选择需要的功能"))
    #     self.ButtonGetAdvantage.setText(_translate("Dialog", "一键获得商品优缺点"))
    #     self.ButtonCompare.setText(_translate("Dialog", "商品对比助手"))
    #     self.pushButton_3.setText(_translate("Dialog", "爆款好物推荐"))
        
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "请选择需要的功能"))
        self.ButtonGetAdvantage.setText(_translate("Dialog", "一键获得商品优缺点"))
        self.ButtonCompare.setText(_translate("Dialog", "商品对比助手"))
        self.pushButton_3.setText(_translate("Dialog", "爆款好物推荐"))
        self.label_2.setText(_translate("Dialog", "TextLabel"))


    def getAdvantagePage(self):
        from getAdvantage import getAdvantage_Dialog
        self.optimal_dialog = QDialog()
        ui = getAdvantage_Dialog()
        ui.setupUi(self.optimal_dialog)
        self.optimal_dialog.exec_()

    def analysis(self):
        print("进行分析")
        from compareAnalysis import compareAnalysis_Dialog
        self.optimal_dialog = QDialog()
        ui = compareAnalysis_Dialog()
        ui.setupUi(self.optimal_dialog)
        self.optimal_dialog.exec_()

    def recommandpart(self):
        from recommand import recommand_Dialog
        self.dialog = QDialog()

        # 使用 Sale_Form 类来设置界面
        ui = recommand_Dialog()
        ui.setupUi(self.dialog)
        self.dialog.exec_()

if __name__ == "__main__":
    QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling)

    app = QApplication(sys.argv)

    # 创建一个 QDialog 对象来显示界面
    dialog = QDialog()

    # 使用 Sale_Form 类来设置界面
    ui = Buy_Form()
    ui.setupUi(dialog)

    # 显示对话框
    dialog.show()

    sys.exit(app.exec_())
