# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sale.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Sale_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(397, 300)
        Form.setMaximumSize(QtCore.QSize(406, 300))
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 60, 151, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.market = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.market.setObjectName("market")
        self.verticalLayout.addWidget(self.market)
        self.optimalPart = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.optimalPart.setObjectName("optimalPart")
        self.verticalLayout.addWidget(self.optimalPart)
        self.competition = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.competition.setObjectName("competition")
        self.verticalLayout.addWidget(self.competition)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 30, 96, 12))
        self.label.setObjectName("label")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(199, 60, 181, 221))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(260, 30, 96, 12))
        self.label_5.setObjectName("label_5")

        self.optimalPart.clicked.connect(self.Optimal)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "卖家页面"))
        self.market.setText(_translate("Form", "市场洞察"))
        self.optimalPart.setText(_translate("Form", "商品数据及优化"))
        self.competition.setText(_translate("Form", "竞品分析"))
        self.label.setText(_translate("Form", "请选择需要的功能"))
        self.label_3.setText(_translate("Form", "市场洞察：\n"
"1.\n"
"2.\n"
"3."))
        self.label_4.setText(_translate("Form", "商品数据及优化：\n"
"1.\n"
"2.\n"
"3."))
        self.label_2.setText(_translate("Form", "竞品分析：\n"
"1.\n"
"2.\n"
"3."))
        self.label_5.setText(_translate("Form", "功能描述："))

    def Optimal(self):
        print("botton")
        from optimal2 import Optimal_Form
        self.Form = QtWidgets.QWidget()
        ui = Optimal_Form()
        ui.setupUi(self.Form)
        self.Form.show()
    
if __name__ == "__main__":
    import sys

    QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling)

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Sale_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
