# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sale2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtWidgets import QApplication, QDialog, QVBoxLayout, QPushButton, QLabel
from PyQt5.QtCore import QObject, QThread, pyqtSignal
import time


class Sale_Form(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(270, 20, 96, 12))
        self.label_5.setObjectName("label_5")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(209, 50, 181, 221))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 50, 151, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 20, 96, 12))
        self.label.setObjectName("label")
        #connect part
        self.pushButton.clicked.connect(self.Optimal)
        self.pushButton_3.clicked.connect(self.analysis)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "商家小助手"))
        self.label_5.setText(_translate("Dialog", "功能描述："))
        self.label_3.setText(_translate("Dialog", "市场洞察：\n"
"1.\n"
"2.\n"
"3."))
        self.label_4.setText(_translate("Dialog", "商品数据及优化：\n"
"1.\n"
"2.\n"
"3."))
        self.label_2.setText(_translate("Dialog", "竞品分析：\n"
"1.\n"
"2.\n"
"3."))
        self.pushButton_2.setText(_translate("Dialog", "市场洞察"))
        self.pushButton.setText(_translate("Dialog", "商品数据及优化"))
        self.pushButton_3.setText(_translate("Dialog", "竞品分析"))
        self.label.setText(_translate("Dialog", "请选择需要的功能"))

    def open_second_window(self):
        # 创建并启动线程执行耗时操作
        self.worker = Worker()
        self.thread = QThread()
        self.worker.moveToThread(self.thread)
        self.worker.finished.connect(self.Optimal)
        self.thread.started.connect(self.worker.run)
        self.thread.start()




    def Optimal(self):
        from optimal3 import Optimal_Dialog
        # print("button")
        self.optimal_dialog = QDialog()
        ui = Optimal_Dialog()
        ui.setupUi(self.optimal_dialog)
        self.optimal_dialog.exec_()

    def analysis(self):
        from competeAnalysis import competeAnalysis_Dialog
        self.optimal_dialog = QDialog()
        ui = competeAnalysis_Dialog()
        ui.setupUi(self.optimal_dialog)
        self.optimal_dialog.exec_()

#多线程
class Worker(QObject):
    finished = pyqtSignal()

    def run(self):
        # 模拟耗时操作
        time.sleep(2)
        self.finished.emit()


if __name__ == "__main__":
    QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling)

    app = QApplication(sys.argv)

    # 创建一个 QDialog 对象来显示界面
    dialog = QDialog()

    # 使用 Sale_Form 类来设置界面
    ui = Sale_Form()
    ui.setupUi(dialog)

    # 显示对话框
    dialog.show()

    sys.exit(app.exec_())
